version: "3.1"
services:
  streamlit: 
    build: 
      dockerfile: Dockerfile.streamlit
      context: .
    command: "streamlit hello"
  gw:
    image: gwrun/gwrun
    command: ["gw", "--url", "http://streamlit:8501", "--secrets", "/run/secrets/tunnel.json"]
    secrets:
      - tunnel.json
secrets:
  tunnel.json:
    file: secrets/tunnel.json
