version: '3.8'
services:
  odoo:
    image: odoo:12.0
    depends_on:
      - db
  db:
    image: postgres:10
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
  gw:
    image: gwrun/gwrun
    command: ["gw", "--url", "http://odoo:8069", "--secrets", "/run/secrets/tunnel.json"]
    secrets:
      - tunnel.json
secrets:
  tunnel.json:
    file: secrets/tunnel.json
